### ISSUE TITLE
64Bit version default folder is c:\Program Files (x86)

### ISSUE THREAD

**Issue by pedgarcia** [tonyt73/AGDX-Studio#1]
Small detail, but the 64bit version installer suggests the 32-bit Program FIles folder by default. It should suggest "C:\Program Files\AGDx Studio"

(*) The 64 after AGDx Studio folder turns redundant.

**Comment by tonyt73** [comment]
Good point. It's an installer thing. Still learning NSIS

**Comment by tonyt73** [comment]
Fixed

**Comment by tonyt73** [comment]
Keeping the 64 in product name so a user can install both SxS

**Comment by tonyt73** [comment]
Ok I relented. :-)
Install folder now without 32 or 64 on the end
