### ISSUE TITLE
Select Directory button not working

### ISSUE THREAD

**Issue by oss003** [tonyt73/AGDX-Studio#10]
In Settings -> Build -> Emulator, the select directory button after Executable isn't working.

![image](https://user-images.githubusercontent.com/4426956/53733703-1b86cb00-3e82-11e9-99da-e5a393d80f58.png)

**Comment by tonyt73** [comment]
Will be available in the next release

[https://github.com/tonyt73/AGDx-Studio/commit/2f4de7b8583fd296560ff4866e43fcdb08029efd](url)
