### ISSUE TITLE
Atom AGD file

### ISSUE THREAD

**Issue by oss003** [tonyt73/AGDX-Studio#11]
AGDX Studio has created an AGD file for the Atom but there are some issues:

- There is no colour attribute at the DEFINEBLOCK definition, this is used for dithering
- After the screendefinition, SPRITEPOSITION starts with a -1 which is the player sprite?????

[AtomTest.zip](https://github.com/tonyt73/AGDx-Studio/files/2931280/AtomTest.zip)

**Comment by tonyt73** [comment]
You should be able to fix this locally be editing the AGDX Studio\GraphicsModes\Acorn Atom Monochrome.json file

Change the section
     "Tile" : {
		"BitmapDataOnly" : true
	 },

To

     "Tile" : {
		"BitmapDataOnly" : false
	 },

**Comment by tonyt73** [comment]
@oss003 What is a valid attribute for monochrome?
Or is this the 4 colour version?

**Comment by oss003** [comment]
It's the monochrome mode.

Changing the json file doesn't make any difference .......
The Atom engine needs the same data as the Spectrum engine, for tiles: type, 8x data,colour attribute.
The colour attribute is missing now in the AGD file for the Atom, also in the 4 colour mode.

**Comment by tonyt73** [comment]
It makes no sense for 4 colour mode to have an attribute.
Atom monochrome is therefore spectrum 16 colour mode and you could simply rename the atom monochrome file and then copy the zx spectrum one to be atom monochrome. Change the name inside the file as well.

**Comment by oss003** [comment]
That doesn't work because when I want to run a game in Atom mode, the colour attribute byte is skipped when generating an AGD file.

There is 1 only Atom engine for monochrome and colourmode and that needs a colour attribute byte for dithering in monochrome mode. I don't care if a 0 is added but the compiler and engine need a colour attribute byte like the Spectrum.

**Comment by tonyt73** [comment]
A hack was implemented to support this.
I will remove this, if/when the Atom AGD compiler removes the need for the attribute.
