### ISSUE TITLE
Version info

### ISSUE THREAD

**Issue by oss003** [tonyt73/AGDX-Studio#12]
I have a version of AGDX installed on my laptop and wanted to see which version it is, so I pressed Help -> About ......

![image](https://user-images.githubusercontent.com/4426956/54387344-6cc16680-469b-11e9-8975-910bcadcc8e9.png)

**Comment by tonyt73** [comment]
Show be fixed from 0.6 onwards

**Comment by tonyt73** [comment]
If it continues; then try running the application in Administrator mode
