### ISSUE TITLE
Create 32bit version of the AGD Compiler

### ISSUE THREAD

**Issue by tonyt73** [tonyt73/AGDX-Studio#15]
64 bit compiler supplied with 32 bit install

**Comment by plirof** [comment]
The Latest version have 64bit compiler.
I run it from linux Wine and it needs the 32bit. 
Can you release a 32bit version?
Thanks

**Comment by tonyt73** [comment]
Sorry I no longer have the development environment installed to make this
anymore.
Also I've stopped working on it.

**Comment by plirof** [comment]
ok Thanks for your work :)
