### ISSUE TITLE
Release version crashes at Foggy example project

### ISSUE THREAD

**Issue by Sgw32** [tonyt73/AGDX-Studio#19]
I just press F9 button after opening example project.

![image](https://user-images.githubusercontent.com/14097148/62331910-17f57f80-b4c6-11e9-9cec-6816b8c225a1.png)

**Comment by zefir1990** [comment]
Try Windows 7 compatibility mode

**Comment by tonyt73** [comment]
Designed for Windows 7 and above
Developed on Windows 10
