### ISSUE TITLE
Tiny fonts and UI glitches when using (super) high-resolution

### ISSUE THREAD

**Issue by pedgarcia** [tonyt73/AGDX-Studio#2]
I've tried the AGDX Studio on my Macbook's Bootcamp windows partition. I noticed that the editor font is way too tiny and the editor status bar shows cut fonts.

It could be the monitor is that retina display (4k) resolution, but even when I change to a lower resolution like 1600x900 the problems persist.

For the editor font, I couldn't find a way to increase the fonts, but I assume it will have something, right?

<img width="668" alt="agdx" src="https://user-images.githubusercontent.com/3932415/53587432-558d5f80-3b58-11e9-8cd9-1d263b9e1f6b.PNG">

**Comment by tonyt73** [comment]
Does Bootcamp have DPI settings? Could you try 200% DPI?

**Comment by tonyt73** [comment]
I'll also add font size to the editor toolbar (and a new toolbar :) )

**Comment by tonyt73** [comment]
Added Inc/Dec font size in code editor.
(Use the Zoom In and Zoom Out buttons on the main toolbar)

Still need to update the icons to a scalable set

**Comment by tonyt73** [comment]
Added DPI fixes and Text zoom to Release 0.2.1
