### ISSUE TITLE
Missing dlls

### ISSUE THREAD

**Issue by bleuge** [tonyt73/AGDX-Studio#22]
Hi, just tested  this version, 

Link date:      7:11 15/03/2023
Company:        Scorpio Designs
Product:        AGD Studio
Prod version:   0.13.6663

I think this dlls/files need to be added: 
doscommandcr280.bpl, running agd studio
cc32c280mt.dll, running launcher 

Don't know if more files are missing, because programs aborts.

**Comment by tonyt73** [comment]
Thanks I'll check those exist in the installer.

**Comment by tonyt73** [comment]
Added the missing DOSCommand.bpl
The cc32c280mt.dll is present in the 32bit install, and not needed in the 64bit install.
