### ISSUE TITLE
CC32C280MT.DLL

### ISSUE THREAD

**Issue by hendrikbez** [tonyt73/AGDX-Studio#26]
Getting Error "The code execution cannot proceed because CC32C280MT.DLL was not found.
Try to search for it, but cannot find it with google search

**Comment by tonyt73** [comment]
It's included in the .iss file (installer file) line 95.
The installer automatically installs the version for your OS.
The DLL is a 32bit DLL, thus you're on a 32 bit OS.

1. What OS are you running?
2. Is the file in the Program Files (x86)\AGD Studio folder?

**Comment by tonyt73** [comment]
closing due to no response and I can't replicate the issue.

**Comment by hendrikbez** [comment]
Good morning, sorry for not replying, forgot about this, due loadshedding evey
Few hours here in South Africa, yes
⁣Get BlueMail for Android ​I have 64 bit for windows 11

Hendrik

**Comment by tonyt73** [comment]
Could you please send me a list of files in the Program Files/AGD Studio
folder?

**Comment by tonyt73** [comment]
You say you are Windows 11 64 bit, but the application is installed in 32 bit mode.
The installer chooses the correct files to install based on the OS type (32 or 64 bit).
So it is very strange for it to install the 32 bit version on 64 bit Windows.

**Comment by hendrikbez** [comment]
Mornjing

Will do a bit later.

*Jesus Christ is Lord*

*Not a swear word*

**Comment by hendrikbez** [comment]
Good morning

Screenshot of folder

[image: Screenshot_2.png]
Greetings
Hendrik

*Jesus Christ is Lord*

*Not a swear word*

**Comment by AlleyRatStudios** [comment]
It installed correctly as 64-bit for me (Windows 11 x64), but the EXE is still looking for the 32-bit DLL.
