### ISSUE TITLE
Feature request: Tiles larger than 8x8.

### ISSUE THREAD

**Issue by ZXKerl** [tonyt73/AGDX-Studio#31]
Feature request: ability to work with tiles larger than 8x8.

**Comment by tonyt73** [comment]
In the map editor you can use the Scratch pad to store large tile layouts.
Select all your tiles and use the copy or move to Scratch pad tool buttons.

If you want to edit multiple tiles together, I'll consider this along with Big Sprites.

**Comment by ZXKerl** [comment]
One of the most annoying things for my graphic designer was that he would design 16x16 tiles using a graphic editor and then had to manually transfer the 8x8 pieces one by one into the MPAGD editor, where they would get disorganized. This made the tile painting process very cumbersome. Being able to create big tiles in ADGStudio and move them around the map with sizes larger than 8x8 would be a great advantage over MPAGD, allowing for more detailed tiles without the 8x8 restriction.

Big sprites in AGD don't work well when moving several 16x16 sprites together, as they end up falling apart. If you could improve this, it would be very useful for large bosses in games.

**Comment by tonyt73** [comment]
Release 0.16.0 has large tile support.
Use File | New Tile Image (Custom Size) Ctrl+Shift+N to create a new large tile.
There is also a icon on the toolbar for it.
You can set each single tile in a tile set to its own block type using the block type tool mode.
