### ISSUE TITLE
Feature request: import MPAGD projects

### ISSUE THREAD

**Issue by ZXKerl** [tonyt73/AGDX-Studio#32]
Feature request: import MPAGD project files

**Comment by tonyt73** [comment]
Could you please supply a fully working MPAGD project to use.

**Comment by ZXKerl** [comment]
I'm sharing two open-source projects for MPAGD :

https://nucleos.itch.io/bubble2023

https://minilop.itch.io/shmupkit

Also, MPAGD can open any TAP file created with recent standard AGD (without music or assembler routines), so any of these games can be saved as project :

https://spectrumcomputing.co.uk/entry/39062/ZX-Spectrum/Bola_ke_Ase

https://spectrumcomputing.co.uk/list?label_id=18994

**Comment by tonyt73** [comment]
https://github.com/tonyt73/AGD-Studio/releases/tag/0.15.0

**Comment by tonyt73** [comment]
Added support for AGD files only.

MPAGD is a binary format and I'll can't be arsed re-engineering it.
Generate a AGD file from MPAGD and import that.
MPAGD has the convert.exe programs to convert TAP's and SNA's. Use that and MPAGD to create your AGD file.
