### ISSUE TITLE
Feature request: a native version for Ubuntu or Linux Mint.

### ISSUE THREAD

**Issue by cheez26** [tonyt73/AGDX-Studio#35]
Hey. I saw your post on the Spectrum Computing forums (gave you a welcome btw :3) and I was wondering about, well, porting this to Linux distros such as Linux Mint and Ubuntu. Thanks in advance.

**Comment by tonyt73** [comment]
I would love to do this, but its not possible.
You can only use Delphi to make native Linux apps with Rad Studio.
C++ Builder is not supported yet, and if it was, it would be the paid version only.
I only use the community version of Rad Studio.
