### ISSUE TITLE
Project treeview item named Controls

### ISSUE THREAD

**Issue by robcode72** [tonyt73/AGDX-Studio#6]
Note: This only happends when I create a new project.

Location:
On the Project TreeView contro, Item Controls: 

When I click on the Item Controls I get a "Access violation"

Thanks

**Comment by robcode72** [comment]
When I create the new project the  file Controls.json is missing. I've made a copy of froggy Controls.json and it works. :-)

**Comment by tonyt73** [comment]
Fixed in 0.3.0
You'll need to delete the old project and start again
