### ISSUE TITLE
Invalid file handle 32 error during installation on Windows 10 64bits

### ISSUE THREAD

**Issue by pedgarcia** [tonyt73/AGDX-Studio#7]

**Comment by pedgarcia** [comment]
I just downloaded version 0.2.2 64-bit version and noticed that during the first steps of the installation, the installer shows an error message "Invalid file handle 32" several times.

It seems it is not preventing the proper installation as the application run fine after it is done, but the message box appears 10 or so times.

![capture](https://user-images.githubusercontent.com/3932415/53685015-0a538800-3ce3-11e9-8ce4-deca56f2c996.PNG)

**Comment by tonyt73** [comment]
Installer issue for your system.
Unable to do much about this.
Please try a different computer.
